namespace CompanyName.ProductName.Admin.Data.Dataseed.Localization
{
    using System.Linq;
    using CompanyName.ProductName.Admin.Core;
    using CompanyName.ProductName.Admin.Data.Dataseed.SeedManagement;
    using CompanyName.ProductName.Admin.Data.Entities;

    public class LanguagesSeed : SeedBase<Language>
    {
        private ApplicationDBContext _DbContext;

        public override void SeedData(ApplicationDBContext dbContext)
        {
            _DbContext = dbContext;

            InsertDefaultTranslationForLanguages();
            AddOrUpdateLanguages();
            AddOrUpdateLanguageTranslations();
        }

        private void AddOrUpdateLanguages()
        {
            AddOrUpdateLanguage(SupportedLanguages.Arabic, "ar", 1);
            AddOrUpdateLanguage(SupportedLanguages.Bulgarian, "bg", 2);
            AddOrUpdateLanguage(SupportedLanguages.Catalan, "ca", 3);
            AddOrUpdateLanguage(SupportedLanguages.Czech, "cs", 4);
            AddOrUpdateLanguage(SupportedLanguages.Danish, "da", 5);
            AddOrUpdateLanguage(SupportedLanguages.German, "de", 6);
            AddOrUpdateLanguage(SupportedLanguages.Greek, "el", 7);
            AddOrUpdateLanguage(SupportedLanguages.English, "en", 8);
            AddOrUpdateLanguage(SupportedLanguages.Spanish, "es", 9);
            AddOrUpdateLanguage(SupportedLanguages.Finnish, "fi", 10);
            AddOrUpdateLanguage(SupportedLanguages.French, "fr", 11);
            AddOrUpdateLanguage(SupportedLanguages.Hebrew, "he", 12);
            AddOrUpdateLanguage(SupportedLanguages.Hungarian, "hu", 13);
            AddOrUpdateLanguage(SupportedLanguages.Icelandic, "is", 14);
            AddOrUpdateLanguage(SupportedLanguages.Italian, "it", 15);
            AddOrUpdateLanguage(SupportedLanguages.Japanese, "ja", 16);
            AddOrUpdateLanguage(SupportedLanguages.Korean, "ko", 17);
            AddOrUpdateLanguage(SupportedLanguages.Dutch, "nl", 18);
            AddOrUpdateLanguage(SupportedLanguages.Norwegian_Bokmal, "no", 19);
            AddOrUpdateLanguage(SupportedLanguages.Polish, "pl", 20);
            AddOrUpdateLanguage(SupportedLanguages.Portuguese, "pt", 21);
            AddOrUpdateLanguage(SupportedLanguages.Romansh, "rm", 22);
            AddOrUpdateLanguage(SupportedLanguages.Romanian, "ro", 23);
            AddOrUpdateLanguage(SupportedLanguages.Russian, "ru", 24);
            AddOrUpdateLanguage(SupportedLanguages.Croatian, "hr", 25);
            AddOrUpdateLanguage(SupportedLanguages.Slovak, "sk", 26);
            AddOrUpdateLanguage(SupportedLanguages.Albanian, "sq", 27);
            AddOrUpdateLanguage(SupportedLanguages.Swedish, "sv", 28);
            AddOrUpdateLanguage(SupportedLanguages.Thai, "th", 29);
            AddOrUpdateLanguage(SupportedLanguages.Turkish, "tr", 30);
            AddOrUpdateLanguage(SupportedLanguages.Urdu, "ur", 31);
            AddOrUpdateLanguage(SupportedLanguages.Indonesian, "id", 32);
            AddOrUpdateLanguage(SupportedLanguages.Ukrainian, "uk", 33);
            AddOrUpdateLanguage(SupportedLanguages.Belarusian, "be", 34);
            AddOrUpdateLanguage(SupportedLanguages.Slovenian, "sl", 35);
            AddOrUpdateLanguage(SupportedLanguages.Estonian, "et", 36);
            AddOrUpdateLanguage(SupportedLanguages.Latvian, "lv", 37);
            AddOrUpdateLanguage(SupportedLanguages.Lithuanian, "lt", 38);
            AddOrUpdateLanguage(SupportedLanguages.Tajik, "tg", 39);
            AddOrUpdateLanguage(SupportedLanguages.Persian, "fa", 40);
            AddOrUpdateLanguage(SupportedLanguages.Vietnamese, "vi", 41);
            AddOrUpdateLanguage(SupportedLanguages.Armenian, "hy", 42);
            AddOrUpdateLanguage(SupportedLanguages.Azerbaijani, "az", 43);
            AddOrUpdateLanguage(SupportedLanguages.Basque, "eu", 44);
            AddOrUpdateLanguage(SupportedLanguages.UpperSorbian, "hsb", 45);
            AddOrUpdateLanguage(SupportedLanguages.Macedonian, "mk", 46);
            AddOrUpdateLanguage(SupportedLanguages.Sotho, "st", 47);
            AddOrUpdateLanguage(SupportedLanguages.Tsonga, "ts", 48);
            AddOrUpdateLanguage(SupportedLanguages.Setswana, "tn", 49);
            AddOrUpdateLanguage(SupportedLanguages.Venda, "ve", 50);
            AddOrUpdateLanguage(SupportedLanguages.Xhosa, "xh", 51);
            AddOrUpdateLanguage(SupportedLanguages.Zulu, "zu", 52);
            AddOrUpdateLanguage(SupportedLanguages.Afrikaans, "af", 53);
            AddOrUpdateLanguage(SupportedLanguages.Georgian, "ka", 54);
            AddOrUpdateLanguage(SupportedLanguages.Faroese, "fo", 55);
            AddOrUpdateLanguage(SupportedLanguages.Hindi, "hi", 56);
            AddOrUpdateLanguage(SupportedLanguages.Maltese, "mt", 57);
            AddOrUpdateLanguage(SupportedLanguages.SamiNorthern, "se", 58);
            AddOrUpdateLanguage(SupportedLanguages.Irish, "ga", 59);
            AddOrUpdateLanguage(SupportedLanguages.Malay, "ms", 60);
            AddOrUpdateLanguage(SupportedLanguages.Kazakh, "kk", 61);
            AddOrUpdateLanguage(SupportedLanguages.Kyrgyz, "ky", 62);
            AddOrUpdateLanguage(SupportedLanguages.Kiswahili, "sw", 63);
            AddOrUpdateLanguage(SupportedLanguages.Turkmen, "tk", 64);
            AddOrUpdateLanguage(SupportedLanguages.UzbekLatin, "uz", 65);
            AddOrUpdateLanguage(SupportedLanguages.Tatar, "tt", 66);
            AddOrUpdateLanguage(SupportedLanguages.Bangla, "bn", 67);
            AddOrUpdateLanguage(SupportedLanguages.Punjabi, "pa", 68);
            AddOrUpdateLanguage(SupportedLanguages.Gujarati, "gu", 69);
            AddOrUpdateLanguage(SupportedLanguages.Odia, "or", 70);
            AddOrUpdateLanguage(SupportedLanguages.Tamil, "ta", 71);
            AddOrUpdateLanguage(SupportedLanguages.Telugu, "te", 72);
            AddOrUpdateLanguage(SupportedLanguages.Kannada, "kn", 73);
            AddOrUpdateLanguage(SupportedLanguages.Malayalam, "ml", 74);
            AddOrUpdateLanguage(SupportedLanguages.Assamese, "as", 75);
            AddOrUpdateLanguage(SupportedLanguages.Marathi, "mr", 76);
            AddOrUpdateLanguage(SupportedLanguages.Sanskrit, "sa", 77);
            AddOrUpdateLanguage(SupportedLanguages.Mongolian, "mn", 78);
            AddOrUpdateLanguage(SupportedLanguages.Tibetan, "bo", 79);
            AddOrUpdateLanguage(SupportedLanguages.Welsh, "cy", 80);
            AddOrUpdateLanguage(SupportedLanguages.Khmer, "km", 81);
            AddOrUpdateLanguage(SupportedLanguages.Lao, "lo", 82);
            AddOrUpdateLanguage(SupportedLanguages.Burmese, "my", 83);
            AddOrUpdateLanguage(SupportedLanguages.Galician, "gl", 84);
            AddOrUpdateLanguage(SupportedLanguages.Konkani, "kok", 85);
            AddOrUpdateLanguage(SupportedLanguages.Sindhi, "sd", 86);
            AddOrUpdateLanguage(SupportedLanguages.Syriac, "syr", 87);
            AddOrUpdateLanguage(SupportedLanguages.Sinhala, "si", 88);
            AddOrUpdateLanguage(SupportedLanguages.Cherokee, "chr", 89);
            AddOrUpdateLanguage(SupportedLanguages.Inuktitut, "iu", 90);
            AddOrUpdateLanguage(SupportedLanguages.Amharic, "am", 91);
            AddOrUpdateLanguage(SupportedLanguages.Tamazight, "tzm", 92);
            AddOrUpdateLanguage(SupportedLanguages.Kashmiri, "ks", 93);
            AddOrUpdateLanguage(SupportedLanguages.Nepali, "ne", 94);
            AddOrUpdateLanguage(SupportedLanguages.Frisian, "fy", 95);
            AddOrUpdateLanguage(SupportedLanguages.Pashto, "ps", 96);
            AddOrUpdateLanguage(SupportedLanguages.Filipino, "fil", 97);
            AddOrUpdateLanguage(SupportedLanguages.Divehi, "dv", 98);
            AddOrUpdateLanguage(SupportedLanguages.Fulah, "ff", 99);
            AddOrUpdateLanguage(SupportedLanguages.Hausa, "ha", 100);
            AddOrUpdateLanguage(SupportedLanguages.Yoruba, "yo", 101);
            AddOrUpdateLanguage(SupportedLanguages.Quechua, "quz", 102);
            AddOrUpdateLanguage(SupportedLanguages.SesothoSaLeboa, "nso", 103);
            AddOrUpdateLanguage(SupportedLanguages.Bashkir, "ba", 104);
            AddOrUpdateLanguage(SupportedLanguages.Luxembourgish, "lb", 105);
            AddOrUpdateLanguage(SupportedLanguages.Greenlandic, "kl", 106);
            AddOrUpdateLanguage(SupportedLanguages.Igbo, "ig", 107);
            AddOrUpdateLanguage(SupportedLanguages.Oromo, "om", 108);
            AddOrUpdateLanguage(SupportedLanguages.Tigrinya, "ti", 109);
            AddOrUpdateLanguage(SupportedLanguages.Guarani, "gn", 110);
            AddOrUpdateLanguage(SupportedLanguages.Hawaiian, "haw", 111);
            AddOrUpdateLanguage(SupportedLanguages.Somali, "so", 112);
            AddOrUpdateLanguage(SupportedLanguages.Yi, "ii", 113);
            AddOrUpdateLanguage(SupportedLanguages.Mapudungun, "arn", 114);
            AddOrUpdateLanguage(SupportedLanguages.Mohawk, "moh", 115);
            AddOrUpdateLanguage(SupportedLanguages.Breton, "br", 116);
            AddOrUpdateLanguage(SupportedLanguages.Uyghur, "ug", 117);
            AddOrUpdateLanguage(SupportedLanguages.Maori, "mi", 118);
            AddOrUpdateLanguage(SupportedLanguages.Occitan, "oc", 119);
            AddOrUpdateLanguage(SupportedLanguages.Corsican, "co", 120);
            AddOrUpdateLanguage(SupportedLanguages.Alsatian, "gsw", 121);
            AddOrUpdateLanguage(SupportedLanguages.Sakha, "sah", 122);
            AddOrUpdateLanguage(SupportedLanguages.Kiche, "quc", 123);
            AddOrUpdateLanguage(SupportedLanguages.Kinyarwanda, "rw", 124);
            AddOrUpdateLanguage(SupportedLanguages.Wolof, "wo", 125);
            AddOrUpdateLanguage(SupportedLanguages.Dari, "prs", 126);
            AddOrUpdateLanguage(SupportedLanguages.ScottishGaelic, "gd", 127);
            AddOrUpdateLanguage(SupportedLanguages.CentralKurdish, "ku", 128);
            AddOrUpdateLanguage(SupportedLanguages.Bemba, "bem", 129);
            AddOrUpdateLanguage(SupportedLanguages.Bena, "bez", 130);
            AddOrUpdateLanguage(SupportedLanguages.Blin, "byn", 131);
            AddOrUpdateLanguage(SupportedLanguages.Bodo, "brx", 132);
            AddOrUpdateLanguage(SupportedLanguages.Chiga, "cgg", 133);
            AddOrUpdateLanguage(SupportedLanguages.CongoSwahili, "swc", 134);
            AddOrUpdateLanguage(SupportedLanguages.Cornish, "kw", 135);
            AddOrUpdateLanguage(SupportedLanguages.Aghem, "agq", 136);
            AddOrUpdateLanguage(SupportedLanguages.Akan, "ak", 137);
            AddOrUpdateLanguage(SupportedLanguages.Asturian, "ast", 138);
            AddOrUpdateLanguage(SupportedLanguages.Asu, "asa", 139);
            AddOrUpdateLanguage(SupportedLanguages.Basaa, "bas", 140);
            AddOrUpdateLanguage(SupportedLanguages.Afar, "aa", 141);
            AddOrUpdateLanguage(SupportedLanguages.Bafia, "ksf", 142);
            AddOrUpdateLanguage(SupportedLanguages.Bamanankan, "bm", 143);
            AddOrUpdateLanguage(SupportedLanguages.Interlingua, "ia", 144);
            AddOrUpdateLanguage(SupportedLanguages.Ganda, "lg", 145);
            AddOrUpdateLanguage(SupportedLanguages.Gusii, "guz", 146);
            AddOrUpdateLanguage(SupportedLanguages.Friulian, "fur", 147);
            AddOrUpdateLanguage(SupportedLanguages.Duala, "dua", 148);
            AddOrUpdateLanguage(SupportedLanguages.Dzongkha, "dz", 149);
            AddOrUpdateLanguage(SupportedLanguages.Embu, "ebu", 150);
            AddOrUpdateLanguage(SupportedLanguages.Ewe, "ee", 151);
            AddOrUpdateLanguage(SupportedLanguages.Ewondo, "ewo", 152);
            AddOrUpdateLanguage(SupportedLanguages.Esperanto, "eo", 153);
            AddOrUpdateLanguage(SupportedLanguages.Kikuyu, "ki", 154);
            AddOrUpdateLanguage(SupportedLanguages.Kabuverdianu, "kea", 155);
            AddOrUpdateLanguage(SupportedLanguages.Kabyle, "kab", 156);
            AddOrUpdateLanguage(SupportedLanguages.Kako, "kkj", 157);
            AddOrUpdateLanguage(SupportedLanguages.Kalenjin, "kln", 158);
            AddOrUpdateLanguage(SupportedLanguages.Kamba, "kam", 159);
            AddOrUpdateLanguage(SupportedLanguages.Javanese, "jv", 160);
            AddOrUpdateLanguage(SupportedLanguages.JolaFonyi, "dyo", 161);
            AddOrUpdateLanguage(SupportedLanguages.Luyia, "luy", 162);
            AddOrUpdateLanguage(SupportedLanguages.LubaKatanga, "lu", 163);
            AddOrUpdateLanguage(SupportedLanguages.Luo, "luo", 164);
            AddOrUpdateLanguage(SupportedLanguages.LowGerman, "nds", 165);
            AddOrUpdateLanguage(SupportedLanguages.Lingala, "ln", 166);
            AddOrUpdateLanguage(SupportedLanguages.Lakota, "lkt", 167);
            AddOrUpdateLanguage(SupportedLanguages.Langi, "lag", 168);
            AddOrUpdateLanguage(SupportedLanguages.KoyraChiini, "khq", 169);
            AddOrUpdateLanguage(SupportedLanguages.KoyraboroSenni, "ses", 170);
            AddOrUpdateLanguage(SupportedLanguages.Kwasio, "nmg", 171);
            AddOrUpdateLanguage(SupportedLanguages.Ossetian, "os", 172);
            AddOrUpdateLanguage(SupportedLanguages.Nuer, "nus", 173);
            AddOrUpdateLanguage(SupportedLanguages.Nyankole, "nyn", 174);
            AddOrUpdateLanguage(SupportedLanguages.Ngiemboon, "nnh", 175);
            AddOrUpdateLanguage(SupportedLanguages.Ngomba, "jgo", 176);
            AddOrUpdateLanguage(SupportedLanguages.NorthNdebele, "nd", 177);
            AddOrUpdateLanguage(SupportedLanguages.Morisyen, "mfe", 178);
            AddOrUpdateLanguage(SupportedLanguages.Mundang, "mua", 179);
            AddOrUpdateLanguage(SupportedLanguages.Nko, "nqo", 180);
            AddOrUpdateLanguage(SupportedLanguages.Nama, "naq", 181);
            AddOrUpdateLanguage(SupportedLanguages.Masai, "mas", 182);
            AddOrUpdateLanguage(SupportedLanguages.Meru, "mer", 183);
            AddOrUpdateLanguage(SupportedLanguages.Meta, "mgo", 184);
            AddOrUpdateLanguage(SupportedLanguages.Manx, "gv", 185);
            AddOrUpdateLanguage(SupportedLanguages.Machame, "jmc", 186);
            AddOrUpdateLanguage(SupportedLanguages.MakhuwaMeetto, "mgh", 187);
            AddOrUpdateLanguage(SupportedLanguages.Makonde, "kde", 188);
            AddOrUpdateLanguage(SupportedLanguages.Malagasy, "mg", 189);
            AddOrUpdateLanguage(SupportedLanguages.Sena, "seh", 190);
            AddOrUpdateLanguage(SupportedLanguages.Shambala, "ksb", 191);
            AddOrUpdateLanguage(SupportedLanguages.Shona, "sn", 192);
            AddOrUpdateLanguage(SupportedLanguages.Sango, "sg", 193);
            AddOrUpdateLanguage(SupportedLanguages.Sangu, "sbp", 194);
            AddOrUpdateLanguage(SupportedLanguages.SouthNdebele, "nr", 195);
            AddOrUpdateLanguage(SupportedLanguages.Soga, "xog", 196);
            AddOrUpdateLanguage(SupportedLanguages.Samburu, "saq", 197);
            AddOrUpdateLanguage(SupportedLanguages.Rwa, "rwk", 198);
            AddOrUpdateLanguage(SupportedLanguages.Saho, "ssy", 199);
            AddOrUpdateLanguage(SupportedLanguages.Ripuarian, "ksh", 200);
            AddOrUpdateLanguage(SupportedLanguages.Rombo, "rof", 201);
            AddOrUpdateLanguage(SupportedLanguages.Rundi, "rn", 202);
            AddOrUpdateLanguage(SupportedLanguages.Vai, "vai", 203);
            AddOrUpdateLanguage(SupportedLanguages.Wolaytta, "wal", 204);
            AddOrUpdateLanguage(SupportedLanguages.Volapük, "vo", 205);
            AddOrUpdateLanguage(SupportedLanguages.Vunjo, "vun", 206);
            AddOrUpdateLanguage(SupportedLanguages.Walser, "wae", 207);
            AddOrUpdateLanguage(SupportedLanguages.Tongan, "to", 208);
            AddOrUpdateLanguage(SupportedLanguages.Tigre, "tig", 209);
            AddOrUpdateLanguage(SupportedLanguages.Teso, "teo", 210);
            AddOrUpdateLanguage(SupportedLanguages.Tasawaq, "twq", 211);
            AddOrUpdateLanguage(SupportedLanguages.StandardMoroccanTamazight, "zgh", 212);
            AddOrUpdateLanguage(SupportedLanguages.Swati, "ss", 213);
            AddOrUpdateLanguage(SupportedLanguages.Tachelhit, "shi", 214);
            AddOrUpdateLanguage(SupportedLanguages.Taita, "dav", 215);
            AddOrUpdateLanguage(SupportedLanguages.Yangben, "yav", 216);
            AddOrUpdateLanguage(SupportedLanguages.Zarma, "dje", 217);
            AddOrUpdateLanguage(SupportedLanguages.Sami_Inari, "smn", 218);
            AddOrUpdateLanguage(SupportedLanguages.Sami_Skolt, "sms", 219);
            AddOrUpdateLanguage(SupportedLanguages.Chinese, "zh", 220);
            AddOrUpdateLanguage(SupportedLanguages.Norwegian_Nynorsk, "nn", 221);
            AddOrUpdateLanguage(SupportedLanguages.Bosnian, "bs", 222);
            AddOrUpdateLanguage(SupportedLanguages.Sami_Southern, "sma", 223);
            AddOrUpdateLanguage(SupportedLanguages.Serbian, "sr", 224);
            AddOrUpdateLanguage(SupportedLanguages.LowerSorbian, "dsb", 225);
            AddOrUpdateLanguage(SupportedLanguages.Sami_Lule, "smj", 226);

            _DbContext.SaveChanges();
        }

        private void AddOrUpdateLanguageTranslations()
        {
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 1, "العربية");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 1, "Arabic");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 1, "Arabe");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 2, "Interlingua");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 2, "Interlingua");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 2, "Interlingua");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 3, "Ganda");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 3, "Ganda");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 3, "Ganda");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 4, "Gusii");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 4, "Gusii");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 4, "Gusii");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 5, "Friulian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 5, "Friulian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 5, "Friulian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 6, "Duala");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 6, "Duala");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 6, "Duala");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 7, "Dzongkha");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 7, "Dzongkha");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 7, "Dzongkha");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 8, "Embu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 8, "Embu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 8, "Embu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 9, "Ewe");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 9, "Ewe");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 9, "Ewe");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 10, "Ewondo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 10, "Ewondo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 10, "Ewondo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 11, "Esperanto");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 11, "Esperanto");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 11, "Esperanto");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 12, "Kikuyu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 12, "Kikuyu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 12, "Kikuyu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 13, "Bamanankan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 13, "Bamanankan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 13, "Bamanankan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 14, "Kabuverdianu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 14, "Kabuverdianu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 14, "Kabuverdianu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 15, "Kako");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 15, "Kako");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 15, "Kako");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 16, "Kalenjin");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 16, "Kalenjin");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 16, "Kalenjin");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 17, "Kamba");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 17, "Kamba");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 17, "Kamba");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 18, "Javanese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 18, "Javanese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 18, "Javanese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 19, "Jola-Fonyi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 19, "Jola-Fonyi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 19, "Jola-Fonyi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 20, "Luyia");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 20, "Luyia");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 20, "Luyia");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 21, "Luba-Katanga");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 21, "Luba-Katanga");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 21, "Luba-Katanga");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 22, "Luo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 22, "Luo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 22, "Luo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 23, "Low German");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 23, "Low German");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 23, "Low German");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 24, "Lingala");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 24, "Lingala");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 24, "Lingala");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 25, "Lakota");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 25, "Lakota");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 25, "Lakota");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 26, "Kabyle");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 26, "Kabyle");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 26, "Kabyle");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 27, "Langi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 27, "Langi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 27, "Langi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 28, "Bafia");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 28, "Bafia");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 28, "Bafia");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 29, "Basaa");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 29, "Basaa");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 29, "Basaa");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 30, "Breton");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 30, "Breton");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 30, "Breton");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 31, "Uyghur");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 31, "Uyghur");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 31, "Uyghur");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 32, "Maori");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 32, "Maori");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 32, "Maori");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 33, "Occitan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 33, "Occitan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 33, "Occitan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 34, "Corsican");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 34, "Corsican");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 34, "Corsican");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 35, "Alsatian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 35, "Alsatian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 35, "Alsatian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 36, "Sakha");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 36, "Sakha");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 36, "Sakha");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 37, "K'iche");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 37, "K'iche");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 37, "K'iche");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 38, "Kinyarwanda");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 38, "Kinyarwanda");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 38, "Kinyarwanda");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 39, "Wolof");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 39, "Wolof");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 39, "Wolof");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 40, "Dari");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 40, "Dari");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 40, "Dari");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 41, "Afar");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 41, "Afar");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 41, "Afar");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 42, "Scottish Gaelic");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 42, "Scottish Gaelic");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 42, "Scottish Gaelic");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 43, "Bemba");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 43, "Bemba");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 43, "Bemba");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 44, "Bena");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 44, "Bena");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 44, "Bena");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 45, "Blin");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 45, "Blin");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 45, "Blin");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 46, "Bodo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 46, "Bodo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 46, "Bodo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 47, "Chiga");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 47, "Chiga");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 47, "Chiga");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 48, "Congo Swahili");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 48, "Congo Swahili");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 48, "Congo Swahili");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 49, "Cornish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 49, "Cornish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 49, "Cornish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 50, "Aghem");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 50, "Aghem");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 50, "Aghem");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 51, "Akan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 51, "Akan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 51, "Akan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 52, "Asturian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 52, "Asturian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 52, "Asturian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 53, "Asu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 53, "Asu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 53, "Asu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 54, "Central Kurdish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 54, "Central Kurdish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 54, "Central Kurdish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 55, "Koyra Chiini");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 55, "Koyra Chiini");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 55, "Koyra Chiini");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 56, "Koyraboro Senni");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 56, "Koyraboro Senni");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 56, "Koyraboro Senni");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 57, "Kwasio");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 57, "Kwasio");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 57, "Kwasio");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 58, "Rombo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 58, "Rombo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 58, "Rombo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 59, "Rundi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 59, "Rundi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 59, "Rundi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 60, "Vai");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 60, "Vai");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 60, "Vai");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 61, "Wolaytta");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 61, "Wolaytta");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 61, "Wolaytta");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 62, "Volapük");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 62, "Volapük");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 62, "Volapük");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 63, "Vunjo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 63, "Vunjo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 63, "Vunjo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 64, "Walser");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 64, "Walser");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 64, "Walser");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 65, "Tongan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 65, "Tongan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 65, "Tongan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 66, "Tigre");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 66, "Tigre");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 66, "Tigre");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 67, "Teso");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 67, "Teso");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 67, "Teso");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 68, "Tasawaq");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 68, "Tasawaq");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 68, "Tasawaq");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 69, "Ripuarian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 69, "Ripuarian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 69, "Ripuarian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 70, "Standard Moroccan Tamazight");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 70, "Standard Moroccan Tamazight");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 70, "Standard Moroccan Tamazight");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 71, "Tachelhit");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 71, "Tachelhit");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 71, "Tachelhit");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 72, "Taita");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 72, "Taita");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 72, "Taita");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 73, "Yangben");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 73, "Yangben");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 73, "Yangben");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 74, "Zarma");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 74, "Zarma");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 74, "Zarma");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 75, "Sami (Inari)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 75, "Sami (Inari)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 75, "Sami (Inari)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 76, "Sami (Skolt)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 76, "Sami (Skolt)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 76, "Sami (Skolt)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 77, "Chinese (Simplified)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 77, "Chinese (Simplified)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 77, "Chinese (Simplified)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 78, "Norwegian (Nynorsk)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 78, "Norwegian (Nynorsk)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 78, "Norwegian (Nynorsk)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 79, "Bosnian (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 79, "Bosnian (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 79, "Bosnian (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 80, "Sami (Southern)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 80, "Sami (Southern)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 80, "Sami (Southern)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 81, "Serbian (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 81, "Serbian (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 81, "Serbian (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 82, "Swati");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 82, "Swati");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 82, "Swati");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 83, "Saho");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 83, "Saho");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 83, "Saho");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 84, "Rwa");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 84, "Rwa");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 84, "Rwa");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 85, "Samburu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 85, "Samburu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 85, "Samburu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 86, "Ossetian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 86, "Ossetian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 86, "Ossetian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 87, "Nuer");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 87, "Nuer");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 87, "Nuer");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 88, "Nyankole");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 88, "Nyankole");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 88, "Nyankole");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 89, "Ngiemboon");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 89, "Ngiemboon");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 89, "Ngiemboon");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 90, "Ngomba");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 90, "Ngomba");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 90, "Ngomba");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 91, "North Ndebele");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 91, "North Ndebele");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 91, "North Ndebele");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 92, "Morisyen");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 92, "Morisyen");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 92, "Morisyen");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 93, "Mundang");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 93, "Mundang");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 93, "Mundang");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 94, "N'ko");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 94, "N'ko");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 94, "N'ko");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 95, "Nama");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 95, "Nama");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 95, "Nama");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 96, "Masai");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 96, "Masai");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 96, "Masai");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 97, "Meru");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 97, "Meru");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 97, "Meru");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 98, "Meta'");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 98, "Meta'");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 98, "Meta'");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 99, "Manx");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 99, "Manx");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 99, "Manx");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 100, "Machame");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 100, "Machame");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 100, "Machame");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 101, "Makhuwa-Meetto");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 101, "Makhuwa-Meetto");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 101, "Makhuwa-Meetto");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 102, "Makonde");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 102, "Makonde");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 102, "Makonde");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 103, "Malagasy");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 103, "Malagasy");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 103, "Malagasy");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 104, "Sena");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 104, "Sena");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 104, "Sena");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 105, "Shambala");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 105, "Shambala");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 105, "Shambala");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 106, "Shona");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 106, "Shona");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 106, "Shona");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 107, "Sango");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 107, "Sango");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 107, "Sango");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 108, "Sangu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 108, "Sangu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 108, "Sangu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 109, "South Ndebele");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 109, "South Ndebele");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 109, "South Ndebele");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 110, "Soga");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 110, "Soga");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 110, "Soga");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 111, "Mohawk");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 111, "Mohawk");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 111, "Mohawk");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 112, "Mapudungun");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 112, "Mapudungun");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 112, "Mapudungun");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 113, "Yi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 113, "Yi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 113, "Yi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 114, "Somali");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 114, "Somali");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 114, "Somali");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 115, "Urdu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 115, "Urdu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 115, "Urdu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 116, "Indonesian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 116, "Indonesian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 116, "Indonesian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 117, "Ukrainian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 117, "Ukrainian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 117, "Ukrainian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 118, "Belarusian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 118, "Belarusian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 118, "Belarusian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 119, "Slovenian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 119, "Slovenian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 119, "Slovenian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 120, "Estonian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 120, "Estonian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 120, "Estonian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 121, "Latvian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 121, "Latvian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 121, "Latvian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 122, "Lithuanian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 122, "Lithuanian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 122, "Lithuanian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 123, "Tajik (Cyrillic)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 123, "Tajik (Cyrillic)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 123, "Tajik (Cyrillic)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 124, "Persian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 124, "Persian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 124, "Persian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 125, "Vietnamese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 125, "Vietnamese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 125, "Vietnamese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 126, "Turkish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 126, "Turkish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 126, "Turkish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 127, "Armenian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 127, "Armenian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 127, "Armenian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 128, "Basque");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 128, "Basque");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 128, "Basque");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 129, "Upper Sorbian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 129, "Upper Sorbian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 129, "Upper Sorbian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 130, "Macedonian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 130, "Macedonian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 130, "Macedonian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 131, "Sotho");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 131, "Sotho");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 131, "Sotho");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 132, "Tsonga");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 132, "Tsonga");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 132, "Tsonga");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 133, "Setswana");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 133, "Setswana");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 133, "Setswana");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 134, "Venda");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 134, "Venda");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 134, "Venda");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 135, "Xhosa");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 135, "Xhosa");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 135, "Xhosa");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 136, "Zulu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 136, "Zulu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 136, "Zulu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 137, "Afrikaans");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 137, "Afrikaans");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 137, "Afrikaans");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 138, "Georgian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 138, "Georgian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 138, "Georgian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 139, "Azerbaijani (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 139, "Azerbaijani (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 139, "Azerbaijani (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 140, "Thai");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 140, "Thai");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 140, "Thai");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 141, "Swedish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 141, "Swedish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 141, "Swedish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 142, "Albanian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 142, "Albanian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 142, "Albanian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 143, "Bulgarian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 143, "Bulgarian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 143, "Bulgarian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 144, "Catalan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 144, "Catalan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 144, "Catalan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 145, "Czech");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 145, "Czech");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 145, "Czech");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 146, "Danish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 146, "Danish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 146, "Danish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 147, "German");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 147, "German");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 147, "German");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 148, "Greek");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 148, "Greek");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 148, "Greek");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 149, "الأنجليزية");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 149, "English");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 149, "Anglais");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 150, "Spanish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 150, "Spanish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 150, "Spanish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 151, "Finnish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 151, "Finnish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 151, "Finnish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 152, "الفرنسية");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 152, "French");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 152, "Français");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 153, "Hebrew");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 153, "Hebrew");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 153, "Hebrew");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 154, "Hungarian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 154, "Hungarian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 154, "Hungarian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 155, "Icelandic");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 155, "Icelandic");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 155, "Icelandic");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 156, "Italian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 156, "Italian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 156, "Italian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 157, "Japanese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 157, "Japanese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 157, "Japanese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 158, "Korean");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 158, "Korean");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 158, "Korean");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 159, "Dutch");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 159, "Dutch");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 159, "Dutch");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 160, "Norwegian (Bokmal)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 160, "Norwegian (Bokmal)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 160, "Norwegian (Bokmal)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 161, "Polish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 161, "Polish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 161, "Polish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 162, "Portuguese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 162, "Portuguese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 162, "Portuguese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 163, "Romansh");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 163, "Romansh");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 163, "Romansh");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 164, "Romanian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 164, "Romanian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 164, "Romanian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 165, "Russian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 165, "Russian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 165, "Russian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 166, "Croatian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 166, "Croatian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 166, "Croatian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 167, "Slovak");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 167, "Slovak");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 167, "Slovak");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 168, "Faroese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 168, "Faroese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 168, "Faroese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 169, "Lower Sorbian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 169, "Lower Sorbian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 169, "Lower Sorbian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 170, "Hindi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 170, "Hindi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 170, "Hindi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 171, "Sami (Northern)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 171, "Sami (Northern)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 171, "Sami (Northern)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 172, "Sinhala");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 172, "Sinhala");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 172, "Sinhala");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 173, "Cherokee");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 173, "Cherokee");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 173, "Cherokee");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 174, "Inuktitut (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 174, "Inuktitut (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 174, "Inuktitut (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 175, "Amharic");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 175, "Amharic");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 175, "Amharic");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 176, "Tamazight (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 176, "Tamazight (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 176, "Tamazight (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 177, "Kashmiri");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 177, "Kashmiri");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 177, "Kashmiri");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 178, "Nepali");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 178, "Nepali");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 178, "Nepali");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 179, "Frisian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 179, "Frisian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 179, "Frisian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 180, "Pashto");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 180, "Pashto");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 180, "Pashto");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 181, "Filipino");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 181, "Filipino");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 181, "Filipino");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 182, "Divehi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 182, "Divehi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 182, "Divehi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 183, "Syriac");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 183, "Syriac");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 183, "Syriac");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 184, "Fulah");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 184, "Fulah");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 184, "Fulah");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 185, "Yoruba");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 185, "Yoruba");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 185, "Yoruba");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 186, "Quechua");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 186, "Quechua");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 186, "Quechua");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 187, "Sesotho sa Leboa");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 187, "Sesotho sa Leboa");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 187, "Sesotho sa Leboa");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 188, "Bashkir");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 188, "Bashkir");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 188, "Bashkir");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 189, "Luxembourgish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 189, "Luxembourgish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 189, "Luxembourgish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 190, "Greenlandic");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 190, "Greenlandic");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 190, "Greenlandic");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 191, "Igbo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 191, "Igbo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 191, "Igbo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 192, "Oromo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 192, "Oromo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 192, "Oromo");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 193, "Tigrinya");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 193, "Tigrinya");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 193, "Tigrinya");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 194, "Guarani");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 194, "Guarani");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 194, "Guarani");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 195, "Hawaiian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 195, "Hawaiian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 195, "Hawaiian");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 196, "Hausa (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 196, "Hausa (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 196, "Hausa (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 197, "Sindhi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 197, "Sindhi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 197, "Sindhi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 198, "Konkani");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 198, "Konkani");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 198, "Konkani");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 199, "Galician");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 199, "Galician");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 199, "Galician");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 200, "Irish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 200, "Irish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 200, "Irish");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 201, "Malay");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 201, "Malay");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 201, "Malay");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 202, "Kazakh");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 202, "Kazakh");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 202, "Kazakh");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 203, "Kyrgyz");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 203, "Kyrgyz");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 203, "Kyrgyz");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 204, "Kiswahili");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 204, "Kiswahili");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 204, "Kiswahili");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 205, "Turkmen");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 205, "Turkmen");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 205, "Turkmen");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 206, "Uzbek (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 206, "Uzbek (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 206, "Uzbek (Latin)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 207, "Tatar");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 207, "Tatar");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 207, "Tatar");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 208, "Bangla");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 208, "Bangla");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 208, "Bangla");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 209, "Punjabi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 209, "Punjabi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 209, "Punjabi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 210, "Gujarati");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 210, "Gujarati");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 210, "Gujarati");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 211, "Odia");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 211, "Odia");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 211, "Odia");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 212, "Tamil");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 212, "Tamil");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 212, "Tamil");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 213, "Telugu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 213, "Telugu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 213, "Telugu");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 214, "Kannada");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 214, "Kannada");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 214, "Kannada");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 215, "Malayalam");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 215, "Malayalam");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 215, "Malayalam");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 216, "Assamese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 216, "Assamese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 216, "Assamese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 217, "Marathi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 217, "Marathi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 217, "Marathi");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 218, "Sanskrit");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 218, "Sanskrit");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 218, "Sanskrit");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 219, "Mongolian (Cyrillic)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 219, "Mongolian (Cyrillic)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 219, "Mongolian (Cyrillic)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 220, "Tibetan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 220, "Tibetan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 220, "Tibetan");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 221, "Welsh");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 221, "Welsh");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 221, "Welsh");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 222, "Khmer");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 222, "Khmer");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 222, "Khmer");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 223, "Lao");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 223, "Lao");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 223, "Lao");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 224, "Burmese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 224, "Burmese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 224, "Burmese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 225, "Maltese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 225, "Maltese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 225, "Maltese");
            AddOrUpdateLanguageTranslation(SupportedLanguages.Arabic, 226, "Sami (Lule)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.English, 226, "Sami (Lule)");
            AddOrUpdateLanguageTranslation(SupportedLanguages.French, 226, "Sami (Lule)");

            _DbContext.SaveChanges();
        }

        private void AddOrUpdateLanguage(SupportedLanguages supportedLanguage, string languageCode, int translationId)
        {
            var language = _DbContext.Languages.Find((int)supportedLanguage);

            if (language == null)
            {
                language = new Language
                {
                    Id = (int)supportedLanguage,
                    NameTranslationID = translationId
                };

                _DbContext.Languages.Add(language);
            }

            language.Code = languageCode;
        }

        private void AddOrUpdateLanguageTranslation(SupportedLanguages language, int translationID, string translation)
        {
            var translationEntry = _DbContext.TranslationEntries.Find(translationID, (int)language);

            if (translationEntry == null)
            {
                translationEntry = new TranslationEntry
                {
                    LanguageId = (int)language,
                    TranslationId = translationID,
                    Translation = translation
                };

                _DbContext.TranslationEntries.Add(translationEntry);
            }
            else
            {
                translationEntry.Translation = translation;
            }
        }

        private void InsertDefaultTranslationForLanguages()
        {
            if (!_DbContext.Translations.Any())
            {
                _DbContext.Translations.Add(new Translation { DefaultValue = "Arabic" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Bulgarian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Catalan" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Czech" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Danish" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "German" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Greek" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "English" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Spanish" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Finnish" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "French" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Hebrew" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Hungarian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Icelandic" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Italian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Japanese" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Korean" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Dutch" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Norwegian (Bokmal)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Polish" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Portuguese" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Romansh" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Romanian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Russian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Croatian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Slovak" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Albanian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Swedish" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Thai" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Turkish" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Urdu" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Indonesian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Ukrainian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Belarusian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Slovenian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Estonian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Latvian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Lithuanian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Tajik (Cyrillic)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Persian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Vietnamese" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Armenian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Azerbaijani (Latin)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Basque" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Upper Sorbian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Macedonian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Sotho" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Tsonga" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Setswana" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Venda" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Xhosa" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Zulu" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Afrikaans" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Georgian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Faroese" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Hindi" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Maltese" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Sami (Northern)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Irish" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Malay" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Kazakh" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Kyrgyz" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Kiswahili" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Turkmen" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Uzbek (Latin)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Tatar" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Bangla" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Punjabi" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Gujarati" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Odia" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Tamil" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Telugu" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Kannada" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Malayalam" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Assamese" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Marathi" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Sanskrit" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Mongolian (Cyrillic)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Tibetan" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Welsh" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Khmer" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Lao" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Burmese" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Galician" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Konkani" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Sindhi" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Syriac" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Sinhala" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Cherokee" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Inuktitut (Latin)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Amharic" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Tamazight (Latin)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Kashmiri" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Nepali" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Frisian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Pashto" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Filipino" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Divehi" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Fulah" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Hausa (Latin)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Yoruba" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Quechua" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Sesotho sa Leboa" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Bashkir" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Luxembourgish" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Greenlandic" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Igbo" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Oromo" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Tigrinya" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Guarani" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Hawaiian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Somali" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Yi" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Mapudungun" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Mohawk" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Breton" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Uyghur" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Maori" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Occitan" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Corsican" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Alsatian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Sakha" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "K'iche" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Kinyarwanda" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Wolof" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Dari" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Scottish Gaelic" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Central Kurdish" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Bemba" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Bena" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Blin" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Bodo" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Chiga" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Congo Swahili" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Cornish" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Aghem" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Akan" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Asturian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Asu" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Basaa" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Afar" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Bafia" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Bamanankan" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Interlingua" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Ganda" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Gusii" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Friulian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Duala" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Dzongkha" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Embu" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Ewe" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Ewondo" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Esperanto" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Kikuyu" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Kabuverdianu" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Kabyle" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Kako" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Kalenjin" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Kamba" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Javanese" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Jola-Fonyi" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Luyia" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Luba-Katanga" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Luo" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Low German" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Lingala" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Lakota" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Langi" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Koyra Chiini" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Koyraboro Senni" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Kwasio" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Ossetian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Nuer" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Nyankole" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Ngiemboon" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Ngomba" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "North Ndebele" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Morisyen" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Mundang" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "N'ko" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Nama" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Masai" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Meru" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Meta'" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Manx" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Machame" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Makhuwa-Meetto" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Makonde" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Malagasy" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Sena" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Shambala" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Shona" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Sango" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Sangu" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "South Ndebele" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Soga" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Samburu" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Rwa" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Saho" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Ripuarian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Rombo" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Rundi" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Vai" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Wolaytta" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Volapük" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Vunjo" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Walser" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Tongan" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Tigre" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Teso" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Tasawaq" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Standard Moroccan Tamazight" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Swati" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Tachelhit" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Taita" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Yangben" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Zarma" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Sami (Inari)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Sami (Skolt)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Chinese (Simplified)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Norwegian (Nynorsk)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Bosnian (Latin)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Sami (Southern)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Serbian (Latin)" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Lower Sorbian" });
                _DbContext.Translations.Add(new Translation { DefaultValue = "Sami (Lule)" });

                _DbContext.SaveChanges();
            }
        }
    }
}
